### ISSUE TITLE
infoのjsonファイル出力

### ISSUE THREAD

**Issue by Aodaruma** [furubarug/fanbox-downloader#88]
# 概要

ダウンロードされるディレクトリに生成されるinfo.txtについて、外部プログラムでも処理できるようにjson形式のデータファイルも生成したい

# 想定される動作

ダウンロードされるディレクトリに、json形式のinfoを出力する

いつも利用させていただいています、ありがとうございます！

**Comment by furubarug** [comment]
infoにJSON形式の文字列を入れるとJSONファイルが出力されるようにしました

**Comment by Aodaruma** [comment]
> infoにJSON形式の文字列を入れるとJSONファイルが出力されるようにしました

対応有り難うございます！
早速試してみたのですが、取得された投稿情報のJSONで投稿情報が格納されておらず、空のzipファイルがダウンロードされてしまいます。以下はそのスクリーンショットになります。
![screenshot 2022-03-11 2 01 13](https://user-images.githubusercontent.com/15927814/157721456-fe4b2cdf-18f6-47f2-9ee4-10693cc497dc.png)

**Comment by furubarug** [comment]
過去バージョンのブックマークレットでも空になるので、（おそらく）FANBOXのAPIの仕様が変更されたのだと思われます。
近いうちに対応します。

**Comment by furubarug** [comment]
対応しました。

**Comment by Aodaruma** [comment]
ご対応いただきありがとうございます！
ただ、そのまま実行してみてもJsonファイルが出力されておらず、想定されている動作と違うように思います。 #90 で、Jsonを出力するか確認ダイアログ出現 & setInfoにjsonを出力するよう変更してみたのですが、いかがでしょうか？

**Comment by furubarug** [comment]
PRありがとうございます。
マージしますが、出力情報などは後で調整するかもしれません。
何か欲しい投稿情報などがあれば、またお願いします。
