### ISSUE TITLE
zipダウンロード時、Firefoxで利用すると空の内容のzipがダウンロードされる

### ISSUE THREAD

**Issue by Aodaruma** [furubarug/fanbox-downloader#92]
こんにちは。いつも利用させていただいております。

Firefoxでブックマークレートから利用すると、jsonのコピー→download開始までは実行できるのですが、zipのダウンロード時に、進行度が進んでいるにも関わらず、100%になっても空のzipのままである、という問題が発生しています。

利用しているFirefox Browserは、最新のFirefoxです。
この問題は、現状Firefoxのみで確認しており、OperaやGoogle Chromeでは正常に動作していることは確認済みです。
また、MacOS (macOS Catalina, 10.15.7) 及び Windows 10 (21H2)で、同様の問題が確認しています。

**Comment by furubarug** [comment]
FirefoxのService Workerのセキュリティが厳しくなり、別ドメインを介したダウンロードが制限されるようです。
参考: `https://github.com/jimmywarting/StreamSaver.js/issues/292`

Service Workerの使用を避ける方法として、全ダウンロード終了後に圧縮する方法があります。
しかし、全ダウンロードファイルをメモリ上で持つ必要があるため、パフォーマンスが悪化します。
そのため、しばらくは別ブラウザからの使用を検討していただければと思います。

**Comment by Aodaruma** [comment]
了解しました、では暫くGoogle chrome等で利用させて頂きます。ご対応いただきありがとうございます。
