### ISSUE TITLE
全件指定及び件数指定でのダウンロードができない

### ISSUE THREAD

**Issue by siraisi368** [furubarug/fanbox-downloader#95]
8月に入ってから件数指定・全件指定でのダウンロード(Jsonコピー時)に
``TypeError: Cannot read properties of undefined (reading 'length')``というエラーが発生するようになった
(FireFox環境においては``TypeError: n.body.items is undefined``)

https://github.com/furubarug/fanbox-downloader/blob/c72fc951593c603bd11dd7c2162a2fb0143306ba/fanbox-downloader.ts#L182 
にてhttpGetAsで返却されるObjectに、itemsの定義が存在しないことが原因と思われます。

fork元であるリポジトリのブックマークレットにおいても、同様の問題が発生するため
サイト構造の変更等が影響している可能性があります。

環境:
Chromium Edge Version 127.0.2651.86(公式ビルド) x64
Google Chrome  Version 127.0.6533.100(公式ビルド) x64
Mozilla FireFox Version 128.0.3 x64

**Comment by furubarug** [comment]
仕様変更でページング情報と投稿情報が別URLになったみたいです。
なので先にページング情報とってきて、その結果に対して投稿情報取りに行くようにロジックを修正する必要がありそうですね…
